import test from 'node:test';
import assert from 'node:assert/strict';
import {blankPortfolio,summarize,tfexPnl,validatePortfolio,type Portfolio} from '../lib/portfolio.ts';
// Synthetic fixture (formerly the app's sample portfolio); never shipped to users.
const demoPortfolio:Portfolio={fx:35,platforms:[{id:"dime",name:"Dime!",kind:"แอปลงทุน",notes:""},{id:"innovest",name:"InnovestX",kind:"โบรกเกอร์",notes:""},{id:"kplus",name:"K PLUS",kind:"ธนาคาร",notes:""}],accounts:[{id:"kbank",name:"บัญชีออมทรัพย์กสิกร",bank:"กสิกรไทย",number:"xxx-x-xx458-2",currency:"THB",opening:325000,notes:"ตัวอย่าง"},{id:"scb",name:"บัญชีลงทุนไทย",bank:"ไทยพาณิชย์",number:"xxx-xxx-7291",currency:"THB",opening:247000,notes:"ตัวอย่าง"},{id:"usd",name:"Dime! USD",bank:"Dime!",number:"DEMO-USD",currency:"USD",opening:12500,notes:"ตัวอย่าง"}],trades:[{id:"d1",symbol:"AAPL",name:"Apple Inc.",type:"หุ้นสหรัฐฯ",platform:"dime",account:"usd",currency:"USD",side:"BUY",qty:20,price:185.5,fee:1,date:"2026-08-01",notes:""},{id:"d2",symbol:"NVDA",name:"NVIDIA Corporation",type:"หุ้นสหรัฐฯ",platform:"dime",account:"usd",currency:"USD",side:"BUY",qty:35,price:108.2,fee:1,date:"2026-08-12",notes:""},{id:"d3",symbol:"ADVANC",name:"แอดวานซ์ อินโฟร์ เซอร์วิส",type:"หุ้นไทย",platform:"innovest",account:"scb",currency:"THB",side:"BUY",qty:600,price:245,fee:100,date:"2026-08-18",notes:""},{id:"d4",symbol:"K-USXNDQ",name:"กองทุนเปิดเค ยูเอส หุ้นทุน",type:"กองทุน",platform:"kplus",account:"kbank",currency:"THB",side:"BUY",qty:4200,price:12.8,fee:0,date:"2026-08-25",notes:""}],tfex:[{id:"f1",symbol:"S50U26",platform:"innovest",side:"LONG",qty:2,entry:842.5,exit:855,multiplier:200,fee:140,date:"2026-08-26",closeDate:"2026-08-27",notes:"ตัวอย่าง · ทำตามแผน"},{id:"f2",symbol:"S50U26",platform:"innovest",side:"SHORT",qty:1,entry:860,exit:868,multiplier:200,fee:70,date:"2026-08-28",closeDate:"2026-08-28",notes:"ตัวอย่าง · ตัดขาดทุน"},{id:"f3",symbol:"S50U26",platform:"innovest",side:"LONG",qty:1,entry:850,exit:872,multiplier:200,fee:70,date:"2026-08-29",closeDate:"2026-08-30",notes:"ตัวอย่าง"}],cash:[],quotes:{"AAPL|USD|dime":224.5,"NVDA|USD|dime":131.88,"ADVANC|THB|innovest":284,"K-USXNDQ|THB|kplus":14.36}};

test('THB and USD portfolio reconciles investments, fees, and cash',()=>{const d=validatePortfolio(demoPortfolio),s=summarize(d);assert.equal(s.balances.get('usd'),5001);assert.equal(s.balances.get('kbank'),271240);assert.equal(s.balances.get('scb'),99900);assert.equal(s.total,s.cash+s.invested);assert.equal(s.pnl,7520);});
test('partial sale uses weighted cost and settles net proceeds',()=>{const d=structuredClone(demoPortfolio);d.trades.push({...d.trades[0],id:'sell',side:'SELL',qty:5,price:230,fee:2,date:'2026-09-01'});const s=summarize(validatePortfolio(d));assert.equal(s.balances.get('usd'),6149);assert.equal(s.assets.find(a=>a.symbol==='AAPL')!.qty,15);assert.ok(Math.abs(s.realizedTHB-(1150-2-927.75)*35)<.00001);});
test('rejects overselling including backdated and edited trades',()=>{const d=structuredClone(demoPortfolio);d.trades.push({...d.trades[0],id:'sell',side:'SELL',qty:21,date:'2026-09-01'});assert.throws(()=>validatePortfolio(d),/มากกว่าจำนวน/);d.trades[4].qty=1;d.trades[4].date='2026-07-01';assert.throws(()=>validatePortfolio(d),/มากกว่าจำนวน/);});
test('rejects currency mismatch and insufficient cash',()=>{const d=structuredClone(demoPortfolio);d.trades[0].currency='THB';assert.throws(()=>validatePortfolio(d),/สกุลเงิน/);d.trades[0].currency='USD';d.accounts[2].opening=1;assert.throws(()=>validatePortfolio(d),/ไม่เพียงพอ/);});
test('TFEX long, short, open, and zero-profit calculations',()=>{const t=demoPortfolio.tfex[0];assert.equal(tfexPnl(t),4860);assert.equal(tfexPnl({...t,side:'SHORT'}),-5140);assert.equal(tfexPnl({...t,exit:null,closeDate:null}),null);assert.equal(tfexPnl({...t,exit:t.entry,fee:0}),0);});
test('rejects invalid TFEX closure and fractional contracts',()=>{const d=structuredClone(demoPortfolio);d.tfex[0].closeDate='2026-07-01';assert.throws(()=>validatePortfolio(d));d.tfex[0].closeDate='2026-08-27';d.tfex[0].qty=1.5;assert.throws(()=>validatePortfolio(d));});
test('cash entries and FX affect the correct balances without changing native holdings',()=>{const d=structuredClone(demoPortfolio);d.cash.push({id:'deposit',account:'usd',side:'DEPOSIT',amount:100,date:'2026-09-01',notes:''});const before=summarize(d);d.fx=40;const after=summarize(validatePortfolio(d));assert.equal(after.balances.get('usd'),5101);assert.deepEqual(before.assets,after.assets);assert.ok(after.total>before.total);});
test('empty portfolios and foreign references are handled',()=>{assert.equal(summarize(blankPortfolio()).total,0);const d=structuredClone(demoPortfolio);d.platforms=[];assert.throws(()=>validatePortfolio(d),/ไม่พบ/);});
