"use client";
import {useState,useEffect} from "react";
import {Portfolio,blankPortfolio,summarize} from "@/lib/portfolio";
import {DataViews,EntryDialog,Modal} from "./portfolio-workspace";
import {TfexImportDialog} from "./tfex-import-dialog";
import {Toaster,toast} from "sonner";
import {ArrowUpRight,ArrowDownLeft,Plus,LayoutDashboard,ChartNoAxesCombined,ArrowLeftRight,Wallet,Landmark,BookOpen,ChevronRight,Sprout,ShieldCheck,Eye,LogOut} from "lucide-react";
import type {AppUser} from "@/lib/auth/types";
import {Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from "@/components/ui/sidebar";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from "@/components/ui/table";
const navigation=[["overview","ภาพรวม",LayoutDashboard],["assets","สินทรัพย์ของฉัน",ChartNoAxesCombined],["transactions","รายการซื้อขาย",ArrowLeftRight],["accounts","บัญชีเงินสด",Wallet],["platforms","แพลตฟอร์ม / โบรกเกอร์",Landmark],["tfex","บันทึกการเทรด TFEX",BookOpen]] as const;
const number=(v:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2,minimumFractionDigits:2}).format(v);
const initial=(name:string)=>name.trim().charAt(0).toUpperCase()||"W";
export function Dashboard({user}:{user:AppUser}){
 const [page,setPage]=useState("overview"),[currency,setCurrency]=useState("THB"),[assetTab,setAssetTab]=useState("ทั้งหมด"),[hidden,setHidden]=useState(false);
 const [data,setData]=useState<Portfolio>(blankPortfolio),[revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState(""),[modal,setModal]=useState<Modal>(null);
 const [importOpen,setImportOpen]=useState(false);
 const summary=summarize(data);
 const money=(v:number)=>hidden?"••••••":`${currency==="THB"?"฿":"$"}${number(currency==="THB"?v:v/data.fx)}`;
 const signed=(v:number)=>`${v>=0?"+":"−"}${money(Math.abs(v))}`;
 const assets=summary.assets.map((a,i)=>({...a,platformId:a.platform,platform:data.platforms.find(p=>p.id===a.platform)?.name??"—",color:["#263d31","#77a23c","#84a544","#29966b"][i%4]}));
 const allocation=[...new Set(assets.map(a=>a.type)),"เงินสด"].map((type,i)=>({type,value:type==="เงินสด"?summary.cash:assets.filter(a=>a.type===type).reduce((v,a)=>v+a.value*(a.currency==="USD"?data.fx:1),0),color:["#28523b","#92ad79","#d5ddaf","#eaece2","#b8c9ad"][i%5]})).filter(a=>a.value>0);
 let offset=0;const donutColors=allocation.map(a=>{const start=offset;offset+=a.value/(summary.total||1)*100;return `${a.color} ${start}% ${Math.max(start,offset-.8)}%, white ${Math.max(start,offset-.8)}% ${offset}%`;}).join(",");
 const nav=(id:string)=>setPage(id);
 async function load(){setLoadError("");try{const r=await fetch("/api/portfolio");const result=await r.json() as {error?:string,data?:Portfolio,revision:number};if(!r.ok)throw new Error(result.error);setRevision(result.revision);if(result.data)setData(result.data);setLoaded(true);}catch(e){setLoaded(false);setLoadError(e instanceof Error?e.message:"โหลดข้อมูลไม่ได้");}}
 useEffect(()=>{void load();},[]);
 async function save(next:Portfolio){if(!loaded)throw new Error("กรุณาโหลดพอร์ตสำเร็จก่อนบันทึก");const r=await fetch("/api/portfolio",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({data:next,revision})});const result=await r.json() as {error?:string,data?:Portfolio,revision:number};if(!r.ok)throw new Error(result.error);setData(next);setRevision(result.revision);toast.success("บันทึกข้อมูลเรียบร้อยแล้ว");}
 function open(m:Modal){setModal(m);}
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:"start_wealth_record",title:"เปิดแบบฟอร์มบันทึกการลงทุน",description:"Open a blank record form in Wealth Me Up. This only starts a form and does not save a record.",inputSchema:{type:"object",properties:{kind:{type:"string",enum:["platform","account","trade","tfex","cash"]}},required:["kind"],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const k=(input as {kind?:unknown})?.kind;if(typeof k!=="string"||!["platform","account","trade","tfex","cash"].includes(k))throw new Error("Invalid record kind");open({kind:k as NonNullable<Modal>["kind"]});return {status:"form_opened",kind:k};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort();},[]);
 return <SidebarProvider style={{"--sidebar-width":"245px"} as React.CSSProperties}>
 <Sidebar className="wealth-sidebar"><SidebarHeader><a className="brand" href="/"><span className="brand-icon"><ChartNoAxesCombined size={25}/></span><span>wealth<span className="brand-light"> me up</span><small>MAKE YOUR WEALTH GROW</small></span></a></SidebarHeader><SidebarContent><div className="workspace-tag"><span className="workspace-avatar">W</span><div>พอร์ตส่วนตัว<small>Personal workspace</small></div><ChevronRight size={15}/></div><p className="nav-label">WORKSPACE</p><SidebarMenu>{navigation.map(([id,label,Icon])=><SidebarMenuItem key={id}><NavButton active={page===id} navigate={()=>nav(id)}><Icon size={19}/><span>{label}</span></NavButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="growth-note"><Sprout size={24}/><strong>ความมั่งคั่ง เริ่มจากการบันทึก</strong><p>ดูแลทุกการลงทุนของคุณ<br/>ให้เติบโตไปด้วยกัน</p><div className="note-line"/></div><div className="profile"><span className="profile-avatar">{initial(user.displayName)}</span><div className="profile-text"><span className="profile-name">{user.displayName}</span><small><ShieldCheck size={12}/> {user.email}</small></div><form method="post" action="/auth/logout"><button type="submit" className="logout-button" aria-label="ออกจากระบบ" title="ออกจากระบบ"><LogOut size={16}/></button></form></div></SidebarFooter></Sidebar>
 <div className="app-shell"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>พื้นที่การลงทุน</span><ChevronRight size={14}/><strong>{navigation.find(n=>n[0]===page)?.[1]}</strong></div><div className="top-right"><span className="demo-label">พอร์ตของฉัน</span><span className="top-divider"/><span className="profile-avatar small" title={user.email}>{initial(user.displayName)}</span></div></header><main className="main"><div className="page-heading"><div><div className="eyebrow">YOUR WEALTH, IN ONE PLACE</div><h1>{page==="overview"?"ภาพรวมพอร์ตลงทุน":navigation.find(n=>n[0]===page)?.[1]}<span className="heading-dot">.</span></h1><p>ทุกสินทรัพย์ ทุกบัญชี มองเห็นภาพรวมได้ในที่เดียว</p></div><button className="btn primary" disabled={!loaded} onClick={()=>open({kind:page==="accounts"?"account":page==="platforms"?"platform":page==="tfex"?"tfex":"trade"})}><Plus size={18}/> {page==="accounts"?"เพิ่มบัญชี":page==="platforms"?"เพิ่มแพลตฟอร์ม":page==="tfex"?"บันทึกเทรด":"บันทึกรายการ"}</button></div>
 {loadError?<div className="error-message mb-5" role="alert">{loadError} {loadError.includes("เข้าสู่ระบบ")&&<a className="btn ml-3" href="/login?return_to=%2F">เข้าสู่ระบบ</a>} <button className="text-button inline-flex ml-3" onClick={()=>void load()}>ลองโหลดอีกครั้ง</button></div>:null}
 <div className="toolbar"><div className="portfolio-label"><span className="tiny-dot"/> พอร์ตการลงทุนทั้งหมด <span className="count">{assets.length} สินทรัพย์</span></div><div className="toolbar-right"><button className="text-button fx-button" disabled={!loaded} onClick={()=>open({kind:"fx"})}>1 USD = {data.fx} THB <span className="small-label">· กำหนดเอง</span></button><span className="muted">แสดงมูลค่าใน</span><Tabs value={currency} onValueChange={setCurrency}><TabsList className="currency-tabs"><TabsTrigger value="THB">฿ THB</TabsTrigger><TabsTrigger value="USD">$ USD</TabsTrigger></TabsList></Tabs></div></div>
 {page==="overview"&&<><div className="stats-grid"><section className="stat-card featured"><div className="stat-label">มูลค่าทรัพย์สินทั้งหมด <button aria-label="ซ่อนหรือแสดงมูลค่า" onClick={()=>setHidden(!hidden)}><Eye size={17}/></button></div><div className="stat-value">{money(summary.total)}</div><div className="stat-bottom"><span className="positive-pill">{summary.gain>=0?<ArrowUpRight size={14}/>:<ArrowDownLeft size={14}/>} {summary.cost?(summary.gain/summary.cost*100).toFixed(2):"0.00"}%</span><span>{signed(summary.gain)} จากต้นทุน</span></div><div className="featured-decoration"/></section><section className="stat-card"><div className="stat-label">มูลค่าสินทรัพย์ลงทุน <span className="stat-icon"><ChartNoAxesCombined size={18}/></span></div><div className="stat-value">{money(summary.invested)}</div><div className="stat-bottom"><span className={summary.gain>=0?"positive":"negative"}>{signed(summary.gain)}</span><span className="muted">กำไรที่ยังไม่รับรู้</span></div></section><section className="stat-card"><div className="stat-label">เงินสดคงเหลือ <span className="stat-icon"><Wallet size={18}/></span></div><div className="stat-value">{money(summary.cash)}</div><div className="stat-bottom"><span className="account-dots">{data.accounts.slice(0,3).map(a=><i key={a.id}>{a.bank.slice(0,1)}</i>)}</span><span className="muted">{data.accounts.length} บัญชี · THB และ USD</span></div></section><section className="stat-card"><div className="stat-label">กำไร / ขาดทุน TFEX <span className="stat-icon"><BookOpen size={18}/></span></div><div className={`stat-value ${summary.pnl>=0?"positive":"negative"}`}>{signed(summary.pnl)}</div><div className="stat-bottom"><span className="positive-pill light">Win rate {summary.winRate.toFixed(1)}%</span><span className="muted">{summary.closed} เทรดที่ปิดแล้ว</span></div></section></div>
 <div className="chart-grid"><section className="panel performance"><div className="panel-heading"><div><h2>การเติบโตของพอร์ต</h2><p>มูลค่าสินทรัพย์รวมของคุณ</p></div></div><div className="chart-summary">{money(summary.total)} <span className="positive">มูลค่าประเมินปัจจุบัน</span></div><div className="chart-wrap"><div className="empty-state"><ChartNoAxesCombined className="mx-auto mb-3" size={32}/><p>มูลค่าพอร์ตปัจจุบัน {money(summary.total)}</p><p className="help-text">ยังไม่มีข้อมูลย้อนหลัง<br/>มูลค่าคำนวณจากราคาที่คุณบันทึกล่าสุด</p></div></div></section><section className="panel allocation"><div className="panel-heading"><h2>สัดส่วนสินทรัพย์</h2><span className="small-label">ตามมูลค่า</span></div><div className="donut" style={{background:donutColors?`conic-gradient(${donutColors})`:"#edf0e7"}}><div className="donut-hole"><span>สินทรัพย์ทั้งหมด</span><strong>{allocation.length} <small>ประเภท</small></strong></div></div><div className="allocation-legend">{allocation.map(a=><div key={a.type}><span><i style={{background:a.color}}/>{a.type}</span><strong>{(a.value/(summary.total||1)*100).toFixed(1)}%</strong></div>)}</div></section></div>
 </>}
 {(page==="overview"||page==="assets")&&<section className="panel holdings"><div className="panel-heading"><h2>สินทรัพย์ของฉัน <span className="count">{assets.length}</span></h2><button className="text-button" onClick={()=>nav("assets")}>ดูสินทรัพย์ทั้งหมด <ArrowUpRight size={16}/></button></div><div className="holdings-toolbar"><Tabs value={assetTab} onValueChange={setAssetTab}><TabsList variant="line">{["ทั้งหมด","หุ้นสหรัฐฯ","หุ้นไทย","กองทุน"].map(t=><TabsTrigger value={t} key={t}>{t}</TabsTrigger>)}</TabsList></Tabs><span className="small-label">ราคาประเมินที่บันทึกเอง · คลิกมูลค่าเพื่ออัปเดตราคา</span></div><Table><TableHeader><TableRow>{["สินทรัพย์","แพลตฟอร์ม","จำนวนถือครอง","ต้นทุนเฉลี่ย","มูลค่าปัจจุบัน","กำไร / ขาดทุน"].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{assets.filter(a=>assetTab==="ทั้งหมด"||a.type===assetTab).map(a=><TableRow key={a.key}><TableCell><div className="asset-identity"><span className="asset-logo" style={{background:a.color}}>{a.symbol.slice(0,1)}</span><div><strong>{a.symbol}</strong><small>{a.name}</small></div></div></TableCell><TableCell><span className="platform-pill">{a.platform}</span></TableCell><TableCell>{a.qty.toLocaleString()} <span className="small-label">{a.type==="กองทุน"?"หน่วย":"หุ้น"}</span></TableCell><TableCell>{hidden?"••••••":`${a.currency==="USD"?"$":"฿"}${number(a.avg)}`}</TableCell><TableCell><button className="quote-button" disabled={!loaded} title="อัปเดตราคาประเมิน" onClick={()=>open({kind:"quote",id:a.key})}>{money(a.value*(a.currency==="USD"?data.fx:1))} <PencilIcon/></button></TableCell><TableCell className={a.gain>=0?"positive":"negative"}>{signed(a.gain*(a.currency==="USD"?data.fx:1))}<small>{a.gain>=0?"+":""}{(a.cost?a.gain/a.cost*100:0).toFixed(2)}%</small></TableCell></TableRow>)}</TableBody></Table>{assets.length===0&&<div className="empty-state">ยังไม่มีสินทรัพย์ในพอร์ต<br/><button className="btn primary mt-4" onClick={()=>open({kind:"trade"})}><Plus size={16}/> บันทึกรายการซื้อแรก</button></div>}</section>}
 {page==="overview"&&<div className="bottom-grid"><section className="panel"><div className="panel-heading"><h2>รายการล่าสุด</h2><button className="text-button" onClick={()=>nav("transactions")}>ดูทั้งหมด <ChevronRight size={15}/></button></div>{[...data.trades].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(t=><div className="activity" key={t.id}><span className={`activity-icon ${t.side==="BUY"?"buy":"sell"}`}>{t.side==="BUY"?<ArrowDownLeft size={19}/>:<ArrowUpRight size={19}/>}</span><div><strong>{t.symbol}</strong><small>{t.side==="BUY"?"ซื้อ":"ขาย"} · {data.platforms.find(p=>p.id===t.platform)?.name}</small></div><div className="activity-amount"><strong>{hidden?"••••••":`${t.currency==="USD"?"$":"฿"}${number(t.qty*t.price)}`}</strong><small>{t.qty} หน่วย · {t.date}</small></div></div>)}{!data.trades.length&&<div className="empty-state">ยังไม่มีรายการซื้อขาย</div>}</section><section className="panel"><div className="panel-heading"><h2>บัญชีเงินสด</h2><button className="text-button" onClick={()=>nav("accounts")}>จัดการบัญชี <ChevronRight size={15}/></button></div>{data.accounts.slice(0,3).map(a=><div className="activity" key={a.id}><span className="bank-icon bank-K">{a.bank.slice(0,1)}</span><div><strong>{a.name}</strong><small>{a.bank} · {a.number?"•••• "+a.number.slice(-4):a.currency}</small></div><strong className="activity-amount">{hidden?"••••••":`${a.currency==="USD"?"$":"฿"}${number(summary.balances.get(a.id)??0)}`}</strong></div>)}{!data.accounts.length&&<div className="empty-state">ยังไม่มีบัญชีเงินสด</div>}</section></div>}
 <>{page==="tfex"&&<div className="flex flex-wrap items-center gap-3 mb-5"><button className="btn primary" disabled={!loaded} onClick={()=>setImportOpen(true)}>นำเข้า PDF จาก Pi</button><span className="help-text">อ่านรายการอัตโนมัติ แล้วตรวจสอบก่อนบันทึก</span></div>}</>
 <DataViews page={page} data={data} open={open} money={money}/>
 <footer className="page-footer"><span><ShieldCheck size={14}/> พื้นที่ส่วนตัวสำหรับการลงทุนของคุณ</span><span>wealth me up <span className="footer-sprout">↗</span></span></footer>
 </main></div><EntryDialog modal={modal} close={()=>setModal(null)} data={data} save={save} open={open}/>{importOpen&&<TfexImportDialog data={data} save={save} close={()=>setImportOpen(false)}/>}<Toaster position="top-center" richColors/></SidebarProvider>
}

function PencilIcon(){return <span className="quote-edit">✎</span>}

function NavButton({active,navigate,children}:{active:boolean,navigate:()=>void,children:React.ReactNode}){const {setOpenMobile}=useSidebar();return <SidebarMenuButton className="nav-button" isActive={active} onClick={()=>{navigate();setOpenMobile(false);}}>{children}</SidebarMenuButton>}
