#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

TOTAL_STAGES=4
APP_HOST="wealth-me-up.codex074.com"

banner "wealth-me-up → Google login on ${APP_HOST}"

# ── Stage 1: Google OAuth client ───────────────────────────────────────────
stage "Google Cloud — create the OAuth client the app signs in with"
say "The app now authenticates people itself with Google. It needs an"
say "OAuth 2.0 Web client ID and secret from Google Cloud Console."
open_url "https://console.cloud.google.com/apis/credentials"
step "Pick (or create) a project, e.g. \"wealth-me-up\"."
step "If asked, configure the OAuth consent screen first: User type External,"
step "  app name \"Wealth Me Up\", your email as support/developer contact."
step "  Publishing status \"Testing\" is fine — add your own Google account"
step "  under Test users."
step "Create credentials → OAuth client ID → Application type: Web application."
step "Name: wealth-me-up. Authorized redirect URIs (add both):"
step "  https://${APP_HOST}/auth/google/callback"
step "  http://localhost:5173/auth/google/callback"
step "Create, then copy the Client ID and Client secret."
ask GOOGLE_CLIENT_ID "Paste the Client ID:"
ask_secret GOOGLE_CLIENT_SECRET "Paste the Client secret:"
write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"

# ── Stage 2: app secrets and allowlist ─────────────────────────────────────
stage "App secrets — session key and who may sign in"
existing_secret=$(_existing SESSION_SECRET || true)
if [[ -n "$existing_secret" ]]; then
  note "SESSION_SECRET already set — keeping it (rotate it to sign everyone out)."
  if confirm "Rotate SESSION_SECRET now? (signs out every browser)"; then
    existing_secret=""
  fi
fi
if [[ -z "$existing_secret" ]]; then
  SESSION_SECRET=$(openssl rand -base64 32)
  write_env SESSION_SECRET "$SESSION_SECRET"
fi
default_emails=$(_existing ALLOWED_EMAILS || _existing OWNER_EMAIL || true)
say "Only these Google accounts may use the app (comma-separated, any case)."
[[ -n "$default_emails" && -z "$(_existing ALLOWED_EMAILS || true)" ]] && note "Defaulting to your previous OWNER_EMAIL: ${default_emails}"
ask ALLOWED_EMAILS "Allowed emails:"
[[ -z "$ALLOWED_EMAILS" ]] && ALLOWED_EMAILS="$default_emails"
[[ -z "$ALLOWED_EMAILS" ]] && { warn "ALLOWED_EMAILS cannot be empty"; exit 1; }
write_env ALLOWED_EMAILS "$ALLOWED_EMAILS"
write_env APP_ORIGIN "https://${APP_HOST}"
note "Each allowed email gets its own portfolio, keyed by that email."

# ── Stage 3: Cloudflare — tunnel straight to the app, no Access ────────────
stage "Cloudflare — point the tunnel at the app and remove the Access gate"
say "Cloudflare Access used to be the login wall. The app now has its own,"
say "so Access must be removed or you would sign in twice."
open_url "https://one.dash.cloudflare.com/"
step "Networks → Tunnels → wealth-me-up → Public Hostname → edit ${APP_HOST}:"
step "  Service Type: HTTP   URL: wealth-me-up-web:8787"
step "  Additional settings → Access → turn OFF \"Protect with Access\". Save."
step "Access → Applications → delete the \"Wealth Me Up\" application."
existing_token=$(_existing TUNNEL_TOKEN || true)
if [[ -z "$existing_token" ]]; then
  step "The tunnel token is missing here. Open the tunnel → Configure and copy"
  step "  the token after \"--token \" from the connector command."
  ask_secret TUNNEL_TOKEN "Paste the tunnel token:"
  write_env TUNNEL_TOKEN "$TUNNEL_TOKEN"
else
  note "Keeping the existing TUNNEL_TOKEN."
fi
pause "Press Enter once the hostname points at wealth-me-up-web:8787 with Access off."

# ── Stage 4: build and ship it ─────────────────────────────────────────────
stage "Deploy to pve1"
say "Pack the repo, copy it to pve1, rebuild the image inside the \"docker\""
say "LXC, and restart the stack (app + tunnel). No ports are published."
if confirm "Deploy now? (requires SSH root@pve1)"; then
  "${SCRIPT_DIR}/redeploy.sh"
else
  SKIPPED+=("deploy — run deploy/redeploy.sh manually when ready")
fi

finish
say "Visit https://${APP_HOST} — you should land on the app's own login page"
say "and be able to sign in with an allowed Google account. Then run:"
say "  ssh root@pve1 \"pct exec 103 -- sh -c 'cd /opt/wealth-me-up/deploy && docker compose exec web node deploy/smoke-test.mjs'\""
